# Generated by Django 5.0.3 on 2024-03-18 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionmode',
            old_name='ClientId',
            new_name='Client',
        ),
    ]
