# Generated by Django 5.0.3 on 2024-03-14 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='ClientId',
            new_name='Client',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='StoreGroupId',
            new_name='StoreGroup',
        ),
        migrations.RenameField(
            model_name='storegroup',
            old_name='ClientId',
            new_name='Client',
        ),
        migrations.RenameField(
            model_name='storegroup',
            old_name='StoreGroupId',
            new_name='StoreGroup',
        ),
    ]
