# Generated by Django 5.0.3 on 2024-03-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0002_rename_clientid_transactionmode_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionmode',
            old_name='TransactionId',
            new_name='Id',
        ),
    ]
