# Generated by Django 5.0.3 on 2024-03-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0002_rename_clientid_store_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storegroup',
            old_name='StoreGroup',
            new_name='StoreGroupId',
        ),
    ]
