# Generated by Django 5.0.3 on 2024-03-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0003_rename_storegroup_storegroup_storegroupid'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='EmailId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='MobileNo',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
